language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  REDIS_VERSION: 5.0.0

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker -v
  - docker-compose -v

script:
  - docker-compose up -d server
  - docker-compose up -d cli

after_success:
  - docker-compose ps
  - docker-compose logs
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose push server
  - docker-compose push cli

# don't notify me when things fail
notifications:
  email: false
