sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  REDIS_VERSION: 5.0.0

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker-compose --version

install:
  - docker-compose up -d server cli
  - docker-compose ps 
  - docker-compose logs
