version: '2'
services:

  cli:
    image: redelivre/alpine-redis:cli
    build:
      context: .
      dockerfile: Dockerfile.cli

  server:
    image: redelivre/alpine-redis:server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - "release=$REDIS_VERSION"
        - "username=$USER"
        - "pwd=$redis_pwd"
        - "host=127.0.0.1"
        - "protectedMode=yes"
        - "redisPort=6379"
        - "tcpBacklog=127"
        - "tcpKeepalive=300"
        - "timeout=0"
        - "loglevel=notice"
        - "syslogEnabled=yes"
        - "syslogIdent=redelivreAlpineRedis"
        - "databases=16"
        - "alwaysShowLogo=yes"
        - "rdbCompression=yes"
        - "rdbChecksum=yes"
        - "daemonize=yes"
        - "supervised=no"
        - "slaveServeStaleData=yes"
        - "slaveReadOnly=yes"
        - "replDisklessSync=no"

